// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ex3ModelsAndNewTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ex3ModelsAndNewTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803220053508_Ex3ModelsAndNewTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
